const iconList = {
	academicCap: 'academic-cap',
	annotation: 'annotation',
	archive: 'archive',
	bell: 'bell',
	checkCircle: 'check-circle',
	check: 'check',
	chevronLeft: 'chevron-left',
	chevronRight: 'chevron-right',
	chevronDown: 'chevron-down',
	chevronUp: 'chevron-up',
	clipboardCheck: 'clipboard-check',
	cloudUpload: 'cloud-upload',
	documentText: 'document-text',
	dotsVertical: 'dots-vertical',
	filter: 'filter',
	home: 'home',
	pencilAlt: 'pencil-alt',
	plus: 'plus',
	rating: 'rating',
	refresh: 'refresh',
	search: 'search',
	user: 'user',
	userCircle: 'user-circle',
	viewList: 'view-list',
	x: 'x',
	trash: 'trash',
};

export const icons = Object.freeze(iconList);
